version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "mikeschlottig"
    assignees:
      - "mikeschlottig"
    commit-message:
      prefix: "chore"
      include: "scope"